parameters:

services:
  document.collection_data_provider:
    class: 'AppBundle\DataProvider\DocumentCollectionDataProvider'
    public: true
    autowire: true
    arguments: ['@request_stack', '@api_platform.metadata.resource.metadata_factory', '%api_platform.collection.pagination.items_per_page%']
    tags:
      -  { name: 'api_platform.collection_data_provider' }
  document.item_data_provider:
    class: 'AppBundle\DataProvider\DocumentItemDataProvider'
    public: true
    autowire: true
    tags:
      -  { name: 'api_platform.item_data_provider' }
  document.item_normalizer:
    public: false
    class: 'AppBundle\Serializer\DocumentItemNormalizer'
    arguments:
      - '@api_platform.metadata.resource.metadata_factory'
      - '@api_platform.iri_converter'
      - '@api_platform.resource_class_resolver'
      - '@api_platform.jsonld.context_builder'

    tags:
      - { name: 'serializer.normalizer', priority: 10 }
