parameters:

services:
  document.item_data_provider:
    class: 'AppBundle\DataProvider\DocumentItemDataProvider'
    public: true
    autowire: true
    tags:
      -  { name: 'api_platform.item_data_provider' }
  document.item_data_provider:
    class: 'AppBundle\DataProvider\DocumentCollectionDataProvider'
    public: true
    autowire: true
    tags:
      -  { name: 'api_platform.collection_data_provider' }
